collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6787521
color:
  saturation: 0.3905908
  brandStrength: 0.5236087
  rhythmicContrast: 0.306914
  brandColors:
    - '#55A9DD'
    - '#BCD531'
    - '#FFFFFF'
    - '#F7941D'
    - '#BAD0DB'
  lightness: 0.3220911
layout_spectrum: 0.8819562
name: 'Grace & Harmony Kitchens'
